# Generated by Django 4.2 on 2023-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_date',
            new_name='write_date',
        ),
        migrations.AddField(
            model_name='question',
            name='addFile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='diary', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='diary', max_length=50),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
