# Generated by Django 4.2 on 2023-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_subject_question_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
